services:
  - type: web
    name: micro-frontend
    runtime: static
    repo: https://github.com/boschtech/micro-frontend
    plan: free
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /actuator/health/products
        destination: https://product-service-ua20.onrender.com/actuator/health
      - type: rewrite
        source: /actuator/health/orders
        destination: https://order-service-7342.onrender.com/actuator/health
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_PRODUCT_SERVICE_URL
        sync: false
      - key: VITE_ORDER_SERVICE_URL
        sync: false
